version: "3"
services: 
  app: 
    image: funiber-img
    container_name: funiber-container
    build: ./
    restart: always
    ports:
      - "81:80"
    volumes: 
      - .:/var/www/html
  myadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on: 
      - mysql
    ports:
      - "82:80"
    links:
      - mysql:db
  mysql:
    container_name: mysql
    image: mysql:5.6
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_HOST: 0.0.0.0
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: funiber_db
      MYSQL_USER: funiber
      MYSQL_PASSWORD: secret
volumes:
    mysql:
      driver: "local"
