version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env 
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'